//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Camiher.Libs.Server.DAL.CamiherLocalDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CompradorSet> CompradorSet1
        {
            get
            {
                if ((_CompradorSet1 == null))
                {
                    _CompradorSet1 = base.CreateObjectSet<CompradorSet>("CompradorSet1");
                }
                return _CompradorSet1;
            }
        }
        private ObjectSet<CompradorSet> _CompradorSet1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FotosSet> FotosSet1
        {
            get
            {
                if ((_FotosSet1 == null))
                {
                    _FotosSet1 = base.CreateObjectSet<FotosSet>("FotosSet1");
                }
                return _FotosSet1;
            }
        }
        private ObjectSet<FotosSet> _FotosSet1;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VentaSet> VentaSet
        {
            get
            {
                if ((_VentaSet == null))
                {
                    _VentaSet = base.CreateObjectSet<VentaSet>("VentaSet");
                }
                return _VentaSet;
            }
        }
        private ObjectSet<VentaSet> _VentaSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProveedorSet> ProveedorSet
        {
            get
            {
                if ((_ProveedorSet == null))
                {
                    _ProveedorSet = base.CreateObjectSet<ProveedorSet>("ProveedorSet");
                }
                return _ProveedorSet;
            }
        }
        private ObjectSet<ProveedorSet> _ProveedorSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClientSet> ClientSet
        {
            get
            {
                if ((_ClientSet == null))
                {
                    _ClientSet = base.CreateObjectSet<ClientSet>("ClientSet");
                }
                return _ClientSet;
            }
        }
        private ObjectSet<ClientSet> _ClientSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SaleSet> SaleSet
        {
            get
            {
                if ((_SaleSet == null))
                {
                    _SaleSet = base.CreateObjectSet<SaleSet>("SaleSet");
                }
                return _SaleSet;
            }
        }
        private ObjectSet<SaleSet> _SaleSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NotificationSet> NotificationSet
        {
            get
            {
                if ((_NotificationSet == null))
                {
                    _NotificationSet = base.CreateObjectSet<NotificationSet>("NotificationSet");
                }
                return _NotificationSet;
            }
        }
        private ObjectSet<NotificationSet> _NotificationSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductImageSet> ProductImageSet
        {
            get
            {
                if ((_ProductImageSet == null))
                {
                    _ProductImageSet = base.CreateObjectSet<ProductImageSet>("ProductImageSet");
                }
                return _ProductImageSet;
            }
        }
        private ObjectSet<ProductImageSet> _ProductImageSet;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductsSet> ProductsSet
        {
            get
            {
                if ((_ProductsSet == null))
                {
                    _ProductsSet = base.CreateObjectSet<ProductsSet>("ProductsSet");
                }
                return _ProductsSet;
            }
        }
        private ObjectSet<ProductsSet> _ProductsSet;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CompradorSet1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCompradorSet1(CompradorSet compradorSet)
        {
            base.AddObject("CompradorSet1", compradorSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FotosSet1 EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFotosSet1(FotosSet fotosSet)
        {
            base.AddObject("FotosSet1", fotosSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VentaSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentaSet(VentaSet ventaSet)
        {
            base.AddObject("VentaSet", ventaSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProveedorSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProveedorSet(ProveedorSet proveedorSet)
        {
            base.AddObject("ProveedorSet", proveedorSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClientSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClientSet(ClientSet clientSet)
        {
            base.AddObject("ClientSet", clientSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SaleSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSaleSet(SaleSet saleSet)
        {
            base.AddObject("SaleSet", saleSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NotificationSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotificationSet(NotificationSet notificationSet)
        {
            base.AddObject("NotificationSet", notificationSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductImageSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductImageSet(ProductImageSet productImageSet)
        {
            base.AddObject("ProductImageSet", productImageSet);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductsSet EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductsSet(ProductsSet productsSet)
        {
            base.AddObject("ProductsSet", productsSet);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="ClientSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class ClientSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClientSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static ClientSet CreateClientSet(global::System.String id)
        {
            ClientSet clientSet = new ClientSet();
            clientSet.Id = id;
            return clientSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Surname
        {
            get
            {
                return _Surname;
            }
            set
            {
                OnSurnameChanging(value);
                ReportPropertyChanging("Surname");
                _Surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Surname");
                OnSurnameChanged();
            }
        }
        private global::System.String _Surname;
        partial void OnSurnameChanging(global::System.String value);
        partial void OnSurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String PhoneMain
        {
            get
            {
                return _PhoneMain;
            }
            set
            {
                OnPhoneMainChanging(value);
                ReportPropertyChanging("PhoneMain");
                _PhoneMain = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneMain");
                OnPhoneMainChanged();
            }
        }
        private global::System.String _PhoneMain;
        partial void OnPhoneMainChanging(global::System.String value);
        partial void OnPhoneMainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String PhoneSecond
        {
            get
            {
                return _PhoneSecond;
            }
            set
            {
                OnPhoneSecondChanging(value);
                ReportPropertyChanging("PhoneSecond");
                _PhoneSecond = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneSecond");
                OnPhoneSecondChanged();
            }
        }
        private global::System.String _PhoneSecond;
        partial void OnPhoneSecondChanging(global::System.String value);
        partial void OnPhoneSecondChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Account
        {
            get
            {
                return _Account;
            }
            set
            {
                OnAccountChanging(value);
                ReportPropertyChanging("Account");
                _Account = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Account");
                OnAccountChanged();
            }
        }
        private global::System.String _Account;
        partial void OnAccountChanging(global::System.String value);
        partial void OnAccountChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="CompradorSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class CompradorSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CompradorSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="telefonoM">Initial value of the TelefonoM property.</param>
        /// <param name="telefonoF">Initial value of the TelefonoF property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static CompradorSet CreateCompradorSet(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.String telefonoM, global::System.String telefonoF, global::System.String direccion, global::System.String descripcion, global::System.String email)
        {
            CompradorSet compradorSet = new CompradorSet();
            compradorSet.Id = id;
            compradorSet.Nombre = nombre;
            compradorSet.Apellido = apellido;
            compradorSet.TelefonoM = telefonoM;
            compradorSet.TelefonoF = telefonoF;
            compradorSet.Direccion = direccion;
            compradorSet.Descripcion = descripcion;
            compradorSet.Email = email;
            return compradorSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String TelefonoM
        {
            get
            {
                return _TelefonoM;
            }
            set
            {
                OnTelefonoMChanging(value);
                ReportPropertyChanging("TelefonoM");
                _TelefonoM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefonoM");
                OnTelefonoMChanged();
            }
        }
        private global::System.String _TelefonoM;
        partial void OnTelefonoMChanging(global::System.String value);
        partial void OnTelefonoMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String TelefonoF
        {
            get
            {
                return _TelefonoF;
            }
            set
            {
                OnTelefonoFChanging(value);
                ReportPropertyChanging("TelefonoF");
                _TelefonoF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefonoF");
                OnTelefonoFChanged();
            }
        }
        private global::System.String _TelefonoF;
        partial void OnTelefonoFChanging(global::System.String value);
        partial void OnTelefonoFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="FotosSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class FotosSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FotosSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="path">Initial value of the Path property.</param>
        /// <param name="orden">Initial value of the Orden property.</param>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        public static FotosSet CreateFotosSet(global::System.Int32 id, global::System.String nombre, global::System.String path, global::System.String orden, global::System.String product_ID)
        {
            FotosSet fotosSet = new FotosSet();
            fotosSet.Id = id;
            fotosSet.Nombre = nombre;
            fotosSet.Path = path;
            fotosSet.Orden = orden;
            fotosSet.Product_ID = product_ID;
            return fotosSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Orden
        {
            get
            {
                return _Orden;
            }
            set
            {
                OnOrdenChanging(value);
                ReportPropertyChanging("Orden");
                _Orden = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Orden");
                OnOrdenChanged();
            }
        }
        private global::System.String _Orden;
        partial void OnOrdenChanging(global::System.String value);
        partial void OnOrdenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                OnProduct_IDChanging(value);
                ReportPropertyChanging("Product_ID");
                _Product_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_ID");
                OnProduct_IDChanged();
            }
        }
        private global::System.String _Product_ID;
        partial void OnProduct_IDChanging(global::System.String value);
        partial void OnProduct_IDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="NotificationSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class NotificationSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NotificationSet object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="searchID">Initial value of the SearchID property.</param>
        public static NotificationSet CreateNotificationSet(global::System.String id, global::System.String productID, global::System.String searchID)
        {
            NotificationSet notificationSet = new NotificationSet();
            notificationSet.ID = id;
            notificationSet.ProductID = productID;
            notificationSet.SearchID = searchID;
            return notificationSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.String _ProductID;
        partial void OnProductIDChanging(global::System.String value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String SearchID
        {
            get
            {
                return _SearchID;
            }
            set
            {
                OnSearchIDChanging(value);
                ReportPropertyChanging("SearchID");
                _SearchID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SearchID");
                OnSearchIDChanged();
            }
        }
        private global::System.String _SearchID;
        partial void OnSearchIDChanging(global::System.String value);
        partial void OnSearchIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="ProductImageSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class ProductImageSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductImageSet object.
        /// </summary>
        /// <param name="imageID">Initial value of the ImageID property.</param>
        public static ProductImageSet CreateProductImageSet(global::System.String imageID)
        {
            ProductImageSet productImageSet = new ProductImageSet();
            productImageSet.ImageID = imageID;
            return productImageSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String ImageID
        {
            get
            {
                return _ImageID;
            }
            set
            {
                if (_ImageID != value)
                {
                    OnImageIDChanging(value);
                    ReportPropertyChanging("ImageID");
                    _ImageID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ImageID");
                    OnImageIDChanged();
                }
            }
        }
        private global::System.String _ImageID;
        partial void OnImageIDChanging(global::System.String value);
        partial void OnImageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String ProducID
        {
            get
            {
                return _ProducID;
            }
            set
            {
                OnProducIDChanging(value);
                ReportPropertyChanging("ProducID");
                _ProducID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProducID");
                OnProducIDChanged();
            }
        }
        private global::System.String _ProducID;
        partial void OnProducIDChanging(global::System.String value);
        partial void OnProducIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> Order
        {
            get
            {
                return _Order;
            }
            set
            {
                OnOrderChanging(value);
                ReportPropertyChanging("Order");
                _Order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Order");
                OnOrderChanged();
            }
        }
        private Nullable<global::System.Int32> _Order;
        partial void OnOrderChanging(Nullable<global::System.Int32> value);
        partial void OnOrderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Boolean> Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private Nullable<global::System.Boolean> _Email;
        partial void OnEmailChanging(Nullable<global::System.Boolean> value);
        partial void OnEmailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="ProductsSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class ProductsSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductsSet object.
        /// </summary>
        /// <param name="producto">Initial value of the Producto property.</param>
        /// <param name="marca">Initial value of the Marca property.</param>
        /// <param name="modelo">Initial value of the Modelo property.</param>
        /// <param name="año">Initial value of the Año property.</param>
        /// <param name="potencia">Initial value of the Potencia property.</param>
        /// <param name="peso">Initial value of the Peso property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="precio">Initial value of the Precio property.</param>
        /// <param name="cantidad">Initial value of the Cantidad property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="enventa">Initial value of the Enventa property.</param>
        /// <param name="enbusca">Initial value of the Enbusca property.</param>
        public static ProductsSet CreateProductsSet(global::System.String producto, global::System.String marca, global::System.String modelo, global::System.Int32 año, global::System.Int32 potencia, global::System.Int32 peso, global::System.String descripcion, global::System.Int32 precio, global::System.Int32 cantidad, global::System.String id, global::System.String enventa, global::System.String enbusca)
        {
            ProductsSet productsSet = new ProductsSet();
            productsSet.Producto = producto;
            productsSet.Marca = marca;
            productsSet.Modelo = modelo;
            productsSet.Año = año;
            productsSet.Potencia = potencia;
            productsSet.Peso = peso;
            productsSet.Descripcion = descripcion;
            productsSet.Precio = precio;
            productsSet.Cantidad = cantidad;
            productsSet.Id = id;
            productsSet.Enventa = enventa;
            productsSet.Enbusca = enbusca;
            return productsSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Producto
        {
            get
            {
                return _Producto;
            }
            set
            {
                OnProductoChanging(value);
                ReportPropertyChanging("Producto");
                _Producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Producto");
                OnProductoChanged();
            }
        }
        private global::System.String _Producto;
        partial void OnProductoChanging(global::System.String value);
        partial void OnProductoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Marca
        {
            get
            {
                return _Marca;
            }
            set
            {
                OnMarcaChanging(value);
                ReportPropertyChanging("Marca");
                _Marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Marca");
                OnMarcaChanged();
            }
        }
        private global::System.String _Marca;
        partial void OnMarcaChanging(global::System.String value);
        partial void OnMarcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Modelo
        {
            get
            {
                return _Modelo;
            }
            set
            {
                OnModeloChanging(value);
                ReportPropertyChanging("Modelo");
                _Modelo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Modelo");
                OnModeloChanged();
            }
        }
        private global::System.String _Modelo;
        partial void OnModeloChanging(global::System.String value);
        partial void OnModeloChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Año
        {
            get
            {
                return _Año;
            }
            set
            {
                OnAñoChanging(value);
                ReportPropertyChanging("Año");
                _Año = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Año");
                OnAñoChanged();
            }
        }
        private global::System.Int32 _Año;
        partial void OnAñoChanging(global::System.Int32 value);
        partial void OnAñoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Potencia
        {
            get
            {
                return _Potencia;
            }
            set
            {
                OnPotenciaChanging(value);
                ReportPropertyChanging("Potencia");
                _Potencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Potencia");
                OnPotenciaChanged();
            }
        }
        private global::System.Int32 _Potencia;
        partial void OnPotenciaChanging(global::System.Int32 value);
        partial void OnPotenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Peso
        {
            get
            {
                return _Peso;
            }
            set
            {
                OnPesoChanging(value);
                ReportPropertyChanging("Peso");
                _Peso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Peso");
                OnPesoChanged();
            }
        }
        private global::System.Int32 _Peso;
        partial void OnPesoChanging(global::System.Int32 value);
        partial void OnPesoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Precio
        {
            get
            {
                return _Precio;
            }
            set
            {
                OnPrecioChanging(value);
                ReportPropertyChanging("Precio");
                _Precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Precio");
                OnPrecioChanged();
            }
        }
        private global::System.Int32 _Precio;
        partial void OnPrecioChanging(global::System.Int32 value);
        partial void OnPrecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Cantidad
        {
            get
            {
                return _Cantidad;
            }
            set
            {
                OnCantidadChanging(value);
                ReportPropertyChanging("Cantidad");
                _Cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cantidad");
                OnCantidadChanged();
            }
        }
        private global::System.Int32 _Cantidad;
        partial void OnCantidadChanging(global::System.Int32 value);
        partial void OnCantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Enventa
        {
            get
            {
                return _Enventa;
            }
            set
            {
                OnEnventaChanging(value);
                ReportPropertyChanging("Enventa");
                _Enventa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Enventa");
                OnEnventaChanged();
            }
        }
        private global::System.String _Enventa;
        partial void OnEnventaChanging(global::System.String value);
        partial void OnEnventaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Enbusca
        {
            get
            {
                return _Enbusca;
            }
            set
            {
                OnEnbuscaChanging(value);
                ReportPropertyChanging("Enbusca");
                _Enbusca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Enbusca");
                OnEnbuscaChanged();
            }
        }
        private global::System.String _Enbusca;
        partial void OnEnbuscaChanging(global::System.String value);
        partial void OnEnbuscaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String Proveedor_ID
        {
            get
            {
                return _Proveedor_ID;
            }
            set
            {
                OnProveedor_IDChanging(value);
                ReportPropertyChanging("Proveedor_ID");
                _Proveedor_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Proveedor_ID");
                OnProveedor_IDChanged();
            }
        }
        private global::System.String _Proveedor_ID;
        partial void OnProveedor_IDChanging(global::System.String value);
        partial void OnProveedor_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> Kilometer
        {
            get
            {
                return _Kilometer;
            }
            set
            {
                OnKilometerChanging(value);
                ReportPropertyChanging("Kilometer");
                _Kilometer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Kilometer");
                OnKilometerChanged();
            }
        }
        private Nullable<global::System.Int32> _Kilometer;
        partial void OnKilometerChanging(Nullable<global::System.Int32> value);
        partial void OnKilometerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> Hours
        {
            get
            {
                return _Hours;
            }
            set
            {
                OnHoursChanging(value);
                ReportPropertyChanging("Hours");
                _Hours = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hours");
                OnHoursChanged();
            }
        }
        private Nullable<global::System.Int32> _Hours;
        partial void OnHoursChanging(Nullable<global::System.Int32> value);
        partial void OnHoursChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public global::System.String PrivateDescription
        {
            get
            {
                return _PrivateDescription;
            }
            set
            {
                OnPrivateDescriptionChanging(value);
                ReportPropertyChanging("PrivateDescription");
                _PrivateDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrivateDescription");
                OnPrivateDescriptionChanged();
            }
        }
        private global::System.String _PrivateDescription;
        partial void OnPrivateDescriptionChanging(global::System.String value);
        partial void OnPrivateDescriptionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="ProveedorSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class ProveedorSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProveedorSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="telefonoM">Initial value of the TelefonoM property.</param>
        /// <param name="telefonoF">Initial value of the TelefonoF property.</param>
        /// <param name="direccion">Initial value of the Direccion property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        public static ProveedorSet CreateProveedorSet(global::System.String id, global::System.String nombre, global::System.String apellido, global::System.String telefonoM, global::System.String telefonoF, global::System.String direccion, global::System.String descripcion, global::System.String email)
        {
            ProveedorSet proveedorSet = new ProveedorSet();
            proveedorSet.Id = id;
            proveedorSet.Nombre = nombre;
            proveedorSet.Apellido = apellido;
            proveedorSet.TelefonoM = telefonoM;
            proveedorSet.TelefonoF = telefonoF;
            proveedorSet.Direccion = direccion;
            proveedorSet.Descripcion = descripcion;
            proveedorSet.Email = email;
            return proveedorSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String TelefonoM
        {
            get
            {
                return _TelefonoM;
            }
            set
            {
                OnTelefonoMChanging(value);
                ReportPropertyChanging("TelefonoM");
                _TelefonoM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefonoM");
                OnTelefonoMChanged();
            }
        }
        private global::System.String _TelefonoM;
        partial void OnTelefonoMChanging(global::System.String value);
        partial void OnTelefonoMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String TelefonoF
        {
            get
            {
                return _TelefonoF;
            }
            set
            {
                OnTelefonoFChanging(value);
                ReportPropertyChanging("TelefonoF");
                _TelefonoF = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TelefonoF");
                OnTelefonoFChanged();
            }
        }
        private global::System.String _TelefonoF;
        partial void OnTelefonoFChanging(global::System.String value);
        partial void OnTelefonoFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="SaleSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class SaleSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SaleSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="client_ID">Initial value of the Client_ID property.</param>
        /// <param name="product_ID">Initial value of the Product_ID property.</param>
        public static SaleSet CreateSaleSet(global::System.String id, global::System.String client_ID, global::System.String product_ID)
        {
            SaleSet saleSet = new SaleSet();
            saleSet.Id = id;
            saleSet.Client_ID = client_ID;
            saleSet.Product_ID = product_ID;
            return saleSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> PriceforClient
        {
            get
            {
                return _PriceforClient;
            }
            set
            {
                OnPriceforClientChanging(value);
                ReportPropertyChanging("PriceforClient");
                _PriceforClient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PriceforClient");
                OnPriceforClientChanged();
            }
        }
        private Nullable<global::System.Int32> _PriceforClient;
        partial void OnPriceforClientChanging(Nullable<global::System.Int32> value);
        partial void OnPriceforClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> PriceClientOffered
        {
            get
            {
                return _PriceClientOffered;
            }
            set
            {
                OnPriceClientOfferedChanging(value);
                ReportPropertyChanging("PriceClientOffered");
                _PriceClientOffered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PriceClientOffered");
                OnPriceClientOfferedChanged();
            }
        }
        private Nullable<global::System.Int32> _PriceClientOffered;
        partial void OnPriceClientOfferedChanging(Nullable<global::System.Int32> value);
        partial void OnPriceClientOfferedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.DateTime> LastEmailDate
        {
            get
            {
                return _LastEmailDate;
            }
            set
            {
                OnLastEmailDateChanging(value);
                ReportPropertyChanging("LastEmailDate");
                _LastEmailDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastEmailDate");
                OnLastEmailDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastEmailDate;
        partial void OnLastEmailDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastEmailDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=true)]
        [DataMember()]
        public Nullable<global::System.Int32> FinalPrice
        {
            get
            {
                return _FinalPrice;
            }
            set
            {
                OnFinalPriceChanging(value);
                ReportPropertyChanging("FinalPrice");
                _FinalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalPrice");
                OnFinalPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _FinalPrice;
        partial void OnFinalPriceChanging(Nullable<global::System.Int32> value);
        partial void OnFinalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Client_ID
        {
            get
            {
                return _Client_ID;
            }
            set
            {
                OnClient_IDChanging(value);
                ReportPropertyChanging("Client_ID");
                _Client_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Client_ID");
                OnClient_IDChanged();
            }
        }
        private global::System.String _Client_ID;
        partial void OnClient_IDChanging(global::System.String value);
        partial void OnClient_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=false, IsNullable=false)]
        [DataMember()]
        public global::System.String Product_ID
        {
            get
            {
                return _Product_ID;
            }
            set
            {
                OnProduct_IDChanging(value);
                ReportPropertyChanging("Product_ID");
                _Product_ID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product_ID");
                OnProduct_IDChanged();
            }
        }
        private global::System.String _Product_ID;
        partial void OnProduct_IDChanging(global::System.String value);
        partial void OnProduct_IDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityType(NamespaceName="Model1", Name="VentaSet")]
    [Serializable()]
    [DataContract(IsReference=true)]
    public partial class VentaSet : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VentaSet object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="precioDado">Initial value of the PrecioDado property.</param>
        /// <param name="precioOfrecido">Initial value of the PrecioOfrecido property.</param>
        /// <param name="correoEnviado">Initial value of the CorreoEnviado property.</param>
        /// <param name="fechaUltimoCorreo">Initial value of the FechaUltimoCorreo property.</param>
        /// <param name="precioFinal">Initial value of the PrecioFinal property.</param>
        /// <param name="comprador_Id">Initial value of the Comprador_Id property.</param>
        /// <param name="product_Id">Initial value of the Product_Id property.</param>
        public static VentaSet CreateVentaSet(global::System.Int32 id, global::System.String precioDado, global::System.String precioOfrecido, global::System.String correoEnviado, global::System.String fechaUltimoCorreo, global::System.String precioFinal, global::System.Int32 comprador_Id, global::System.Int32 product_Id)
        {
            VentaSet ventaSet = new VentaSet();
            ventaSet.Id = id;
            ventaSet.PrecioDado = precioDado;
            ventaSet.PrecioOfrecido = precioOfrecido;
            ventaSet.CorreoEnviado = correoEnviado;
            ventaSet.FechaUltimoCorreo = fechaUltimoCorreo;
            ventaSet.PrecioFinal = precioFinal;
            ventaSet.Comprador_Id = comprador_Id;
            ventaSet.Product_Id = product_Id;
            return ventaSet;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String PrecioDado
        {
            get
            {
                return _PrecioDado;
            }
            set
            {
                if (_PrecioDado != value)
                {
                    OnPrecioDadoChanging(value);
                    ReportPropertyChanging("PrecioDado");
                    _PrecioDado = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PrecioDado");
                    OnPrecioDadoChanged();
                }
            }
        }
        private global::System.String _PrecioDado;
        partial void OnPrecioDadoChanging(global::System.String value);
        partial void OnPrecioDadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String PrecioOfrecido
        {
            get
            {
                return _PrecioOfrecido;
            }
            set
            {
                if (_PrecioOfrecido != value)
                {
                    OnPrecioOfrecidoChanging(value);
                    ReportPropertyChanging("PrecioOfrecido");
                    _PrecioOfrecido = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PrecioOfrecido");
                    OnPrecioOfrecidoChanged();
                }
            }
        }
        private global::System.String _PrecioOfrecido;
        partial void OnPrecioOfrecidoChanging(global::System.String value);
        partial void OnPrecioOfrecidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String CorreoEnviado
        {
            get
            {
                return _CorreoEnviado;
            }
            set
            {
                if (_CorreoEnviado != value)
                {
                    OnCorreoEnviadoChanging(value);
                    ReportPropertyChanging("CorreoEnviado");
                    _CorreoEnviado = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("CorreoEnviado");
                    OnCorreoEnviadoChanged();
                }
            }
        }
        private global::System.String _CorreoEnviado;
        partial void OnCorreoEnviadoChanging(global::System.String value);
        partial void OnCorreoEnviadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String FechaUltimoCorreo
        {
            get
            {
                return _FechaUltimoCorreo;
            }
            set
            {
                if (_FechaUltimoCorreo != value)
                {
                    OnFechaUltimoCorreoChanging(value);
                    ReportPropertyChanging("FechaUltimoCorreo");
                    _FechaUltimoCorreo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("FechaUltimoCorreo");
                    OnFechaUltimoCorreoChanged();
                }
            }
        }
        private global::System.String _FechaUltimoCorreo;
        partial void OnFechaUltimoCorreoChanging(global::System.String value);
        partial void OnFechaUltimoCorreoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.String PrecioFinal
        {
            get
            {
                return _PrecioFinal;
            }
            set
            {
                if (_PrecioFinal != value)
                {
                    OnPrecioFinalChanging(value);
                    ReportPropertyChanging("PrecioFinal");
                    _PrecioFinal = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PrecioFinal");
                    OnPrecioFinalChanged();
                }
            }
        }
        private global::System.String _PrecioFinal;
        partial void OnPrecioFinalChanging(global::System.String value);
        partial void OnPrecioFinalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Comprador_Id
        {
            get
            {
                return _Comprador_Id;
            }
            set
            {
                if (_Comprador_Id != value)
                {
                    OnComprador_IdChanging(value);
                    ReportPropertyChanging("Comprador_Id");
                    _Comprador_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Comprador_Id");
                    OnComprador_IdChanged();
                }
            }
        }
        private global::System.Int32 _Comprador_Id;
        partial void OnComprador_IdChanging(global::System.Int32 value);
        partial void OnComprador_IdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarProperty(EntityKeyProperty=true, IsNullable=false)]
        [DataMember()]
        public global::System.Int32 Product_Id
        {
            get
            {
                return _Product_Id;
            }
            set
            {
                if (_Product_Id != value)
                {
                    OnProduct_IdChanging(value);
                    ReportPropertyChanging("Product_Id");
                    _Product_Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Product_Id");
                    OnProduct_IdChanged();
                }
            }
        }
        private global::System.Int32 _Product_Id;
        partial void OnProduct_IdChanging(global::System.Int32 value);
        partial void OnProduct_IdChanged();

        #endregion
    
    }

    #endregion
    
}
